# Generated by Django 3.2.5 on 2023-01-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_auto_20221201_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
