# Generated by Django 3.2.5 on 2023-01-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_alter_productos_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='fecha_publicacion',
        ),
    ]
