# Generated by Django 3.2.5 on 2023-01-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_remove_productos_fecha_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='stock_disonible',
            new_name='stock_disponible',
        ),
    ]
